# Site settings
baseURL = "https://docs.violinist.io/"
languageCode = "en-us"
title = "Violinist documentation"
theme = "hugo-simpledoc-theme"
pygmentsStyle = "manni"
publishDir = "docs"
disableKinds = ["taxonomyTerm"]
[markup.goldmark]
  [markup.goldmark.extensions]
    definitionList = true
    footnote = true
    linkify = true
    strikethrough = true
    table = true
    taskList = true
    typographer = true
  [markup.goldmark.parser]
    attribute = true
    autoHeadingID = true
    autoHeadingIDType = "github"
  [markup.goldmark.renderer]
    hardWraps = true
    unsafe = false
    xhtml = false
# Site parameters
[params]

    # Meta
    description = "Violinist documentation"
    author = "support@violinist.io"
    keywords = "composer, violinist, php, documentation"

    # Header
    # If not set, site title and meta description will be shown.
    # You may use markdown here
    headerTitle = "Violinist documentation"
    completeExample = """
```
{
  "name": "company/project",
  "description": "My awesome project",
  "require": {
    "vendor/package": "~1.0.0",
  },
  "extra": {
    "violinist": {
      "allow_updates_beyond_constraint": 1,
      "assignees": [],
      "blacklist: [],
      "bundled_packages": [],
      "default_branch": "",
      "number_of_concurrent_updates": 0,
      "one_pull_request_per_package": 0,
      "timeframe_disallowed": 0,
      "timezone": "+0000",
      "update_dev_dependencies": 1,
      "update_with_dependencies": 1
    }
  }
}
```
"""

    # Back-to-top button name
    bttButton = ""
